<?php

namespace Hubleto\App\Custom\IpInfoTest\Controllers;

class FavoriteIps extends \Hubleto\Erp\Controller
{

  // Uncomment this if you want to make your controller publicly
  // available without need for authentication.
  // public bool $requiresAuthenticatedUser = false;

  // Uncomment this if you want to have full control over the response content
  // (default Hubleto's desktop will not be rendered)
  // public bool $hideDefaultDesktop = true;

  /**
   * Returns parameters for the view to be rendered, as well as the
   * path to the view. For more information about controllers see
   * https://developer.hubleto.com/v0/docs/controllers
   *
   * @return void
   * 
   */
  public function prepareView(): void
  {

    // Uncomment this if you want your controller be hookable
    // For more details see http://localhost/hubleto/developer/v0/docs/hooks
    // $this->hookManager()->run('controller:prepare-view-start', [$this]);

    parent::prepareView();

    // Following are sample view parameters generated by
    // the `php hubleto` command. Feel free to modify it.
    // For more details see https://developer.hubleto.com/v0/docs/views,
    // https://developer.hubleto.com/v0/docs/ui, or
    // https://developer.hubleto.com/v0/advanced-development/customizing-ui

    $this->viewParams['now'] = date('Y-m-d H:i:s');
    $this->viewParams['randomNumber'] = rand(1, 1000);

    $this->setView('@Hubleto:App:Custom:IpInfoTest/FavoriteIps.twig');

    // Uncomment this if you want your controller be hookable
    // For more details see http://localhost/hubleto/developer/v0/docs/hooks
    // $this->hookManager()->run('controller:prepare-view-end', [$this]);
  }

}
